GET http://localhost:3000

### Create a post
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Test",
    "content": "fsfdsfsfasdfdsf",
    "sender": "avicii"
}

### Get all posts
GET http://localhost:3000/post

### Get post by ID
GET http://localhost:3000/post/678c41b5a11c3892723ea22c

### Get posts by Sender
GET http://localhost:3000/post?sender=avicii

### Update a post
PUT http://localhost:3000/post/678c41b5a11c3892723ea22c
Content-Type: application/json

{
    "title": "updated",
    "content": "ouiouoiuoiuouio",
    "sender": "avicii2"
}

### Create a Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
    "content": "comment comment yoyoy",
    "postId": "678c41b5a11c3892723ea22c",
    "sender": "not avicii"
}
